server:
  port: 9800

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///website?serverTimezone=UTC
    username: root
    password: 123

  #静态文件请求匹配方式
  mvc:
    static-path-pattern: /**
  #修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

#禁用它的客户端注册行为
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false